# NumPy Operations

In [19]:
import numpy as np

In [29]:
a=np.array([(1,3),(5,7),(9,11)])

In [30]:
b=np.array([(2,4),(6,8),(10,12)])

In [31]:
a.ndim   #no.of dimensions

2

In [32]:
b.itemsize  #size of each element

4

In [33]:
a.dtype   #datatype of the array

dtype('int32')

In [34]:
b.size #length of array

6

In [35]:
b.reshape(2,3) #interchange rows and columns

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [36]:
a[0:3,0]  #slicing 0th element of each row

array([1, 5, 9])

In [38]:
b[1:3,1] #slicing 1st element from 1,2 rows

array([ 8, 12])

In [46]:
c=np.linspace(1,5,10) #returns evenly spaced 10 no.s between (1,10)
c

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [43]:
b.sum(0) #sum of elements in each column

array([18, 24])

In [45]:
b.sum(1)  #sum of elements in each row

array([ 6, 14, 22])

In [47]:
np.sqrt(a)    #square root of each element

array([[1.        , 1.73205081],
       [2.23606798, 2.64575131],
       [3.        , 3.31662479]])

In [48]:
np.std(b)   #standard deviation of all elements

3.415650255319866

In [50]:
a+b     #addition of elements of a,b in similar positions

array([[ 3,  7],
       [11, 15],
       [19, 23]])

In [51]:
a-b   #subtraction

array([[-1, -1],
       [-1, -1],
       [-1, -1]])

In [52]:
a*b   #multiplication

array([[  2,  12],
       [ 30,  56],
       [ 90, 132]])

In [54]:
b/a  #division

array([[2.        , 1.33333333],
       [1.2       , 1.14285714],
       [1.11111111, 1.09090909]])

In [57]:
b%a #modulus

array([[0, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [65]:
np.vstack(b)   #vertical stack

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [66]:
np.hstack(a)  #horizantal stack

array([ 1,  3,  5,  7,  9, 11])

In [62]:
np.ravel(a)  #all elements in a single row

array([ 1,  3,  5,  7,  9, 11])

In [70]:
np.max(a) #maximum value among elements

11

In [71]:
np.min(b)  #minimum value among elements

2

In [72]:
e=(np.ravel(a))+(np.ravel(b))  #adding the elements of raveled arrays a and b
e 

array([ 3,  7, 11, 15, 19, 23])